# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=60, verbose_name='用户密码')),
                ('user_tel', models.CharField(max_length=11, verbose_name='用户手机号')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ushou', models.CharField(default='', max_length=100, verbose_name='收获地址')),
                ('uname', models.CharField(default='', max_length=30, verbose_name='收货人')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='收货号码')),
                ('upost', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
