# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180511_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='ushou',
            field=models.CharField(default='', max_length=500, verbose_name='收获地址'),
        ),
    ]
