# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('order_many', models.CharField(max_length=10, verbose_name='收货人')),
                ('order_site', models.CharField(max_length=30, verbose_name='收货地址')),
                ('order_tel', models.CharField(max_length=11, verbose_name='收货电话')),
                ('order_status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款')])),
            ],
        ),
    ]
