# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('order_many', models.CharField(max_length=10, verbose_name='收货人')),
                ('order_site', models.CharField(max_length=30, verbose_name='收货地址')),
                ('order_tel', models.CharField(max_length=11, verbose_name='收货电话')),
                ('order_status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款')], verbose_name='订单状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='订单对应的商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='订单对应的用户ID')),
            ],
        ),
    ]
